// <auto-generated />
using System;
using CSV.Api.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSV.Api.Migrations
{
    [DbContext(typeof(CsvDbContext))]
    [Migration("20210624182742_DataSetTables")]
    partial class DataSetTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSV.Api.DB.DataItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DatasetId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId");

                    b.ToTable("DataItem");
                });

            modelBuilder.Entity("CSV.Api.DB.DataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Average")
                        .HasColumnType("float");

                    b.Property<string>("Buckets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StdDeviation")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("DataSet");
                });

            modelBuilder.Entity("CSV.Api.DB.DataItem", b =>
                {
                    b.HasOne("CSV.Api.DB.DataSet", "Dataset")
                        .WithMany("DataItems")
                        .HasForeignKey("DatasetId");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("CSV.Api.DB.DataSet", b =>
                {
                    b.Navigation("DataItems");
                });
#pragma warning restore 612, 618
        }
    }
}
